using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Tyresoles.Sql.Generators
{
    [Generator(LanguageNames.CSharp)]
    public class EntityQueryGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // 1. Discover all classes decorated with [NavTable]
            var provider = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: (s, _) => s is ClassDeclarationSyntax c && c.AttributeLists.Count > 0,
                transform: (ctx, _) => GetClassSymbolIfNavTable(ctx))
            .Where(t => t != null);

            // 2. Output the source models
            context.RegisterSourceOutput(provider, (ctx, typeSymbol) => ExecuteGeneration(ctx, typeSymbol!));
        }

        private static INamedTypeSymbol? GetClassSymbolIfNavTable(GeneratorSyntaxContext context)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;
            
            foreach (var attributeList in classDeclaration.AttributeLists)
            {
                foreach (var attribute in attributeList.Attributes)
                {
                    var name = attribute.Name.ToString();
                    if (name.Contains("NavTable") || name.Contains("NavTableAttribute"))
                    {
                        var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;
                        return symbol;
                    }
                }
            }
            return null;
        }

        private static void ExecuteGeneration(SourceProductionContext context, INamedTypeSymbol typeSymbol)
        {
            var className = typeSymbol.Name;
            var @namespace = typeSymbol.ContainingNamespace.ToDisplayString();

            // Collect properties
            var properties = new List<IPropertySymbol>();
            var members = typeSymbol.GetMembers();
            foreach (var member in members)
            {
                if (member is IPropertySymbol property && property.SetMethod != null && property.DeclaredAccessibility == Accessibility.Public)
                {
                    properties.Add(property);
                }
            }

            // Emit zero-allocation Mapper
            var mapperSource = GenerateMapperSource(@namespace, className, properties);
            context.AddSource($"{className}Mapper.g.cs", SourceText.From(mapperSource, Encoding.UTF8));

            // Emit Queryable provider extension / GraphQL bindings
            var queryExtensionSource = GenerateQueryExtensionSource(@namespace, className);
            context.AddSource($"{className}QueryExtensions.g.cs", SourceText.From(queryExtensionSource, Encoding.UTF8));
        }

        private static string GenerateMapperSource(string ns, string className, List<IPropertySymbol> properties)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This code was generated by Tyresoles.Sql.Generators to completely bypass reflection at runtime.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Data;");
            sb.AppendLine("using Tyresoles.Sql.Core.Materialization;");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine($"    public static class {className}Mapper");
            sb.AppendLine("    {");
            
            // Method
            sb.AppendLine($"        public static {className} Parse(IDataReader reader)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var entity = new {className}();");
            
            // Native mapping logic
            sb.AppendLine("            for (int i = 0; i < reader.FieldCount; i++)");
            sb.AppendLine("            {");
            sb.AppendLine("                var colName = reader.GetName(i);");
            sb.AppendLine("                if (reader.IsDBNull(i)) continue;");
            sb.AppendLine();
            sb.AppendLine("                switch (colName)");
            sb.AppendLine("                {");
            
            foreach (var prop in properties)
            {
                var colAttr = prop.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == "NavColumnAttribute");
                var colName = colAttr?.ConstructorArguments.FirstOrDefault().Value?.ToString() ?? prop.Name;
                
                sb.AppendLine($"                    case \"{colName}\":");
                
                var typeStr = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                // Map DataReader typed outputs efficiently avoiding Boxing where possible based on typical NavTypes
                if (typeStr.Contains("int") && !typeStr.Contains("byte")) sb.AppendLine($"                        entity.{prop.Name} = reader.GetInt32(i); break;");
                else if (typeStr.Contains("string")) sb.AppendLine($"                        entity.{prop.Name} = reader.GetString(i); break;");
                else if (typeStr.Contains("decimal")) sb.AppendLine($"                        entity.{prop.Name} = reader.GetDecimal(i); break;");
                else if (typeStr.Contains("DateTime")) sb.AppendLine($"                        entity.{prop.Name} = reader.GetDateTime(i); break;");
                else if (typeStr.Contains("Guid")) sb.AppendLine($"                        entity.{prop.Name} = reader.GetGuid(i); break;");
                else if (typeStr.Contains("byte") && !typeStr.Contains("byte[]")) sb.AppendLine($"                        entity.{prop.Name} = reader.GetByte(i); break;");
                else sb.AppendLine($"                        entity.{prop.Name} = ({typeStr})reader.GetValue(i); break;"); // Ultimate fallback
            }
            
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("            return entity;");
            sb.AppendLine("        }");
            
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string GenerateQueryExtensionSource(string ns, string className)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This code was generated by Tyresoles.Sql.Generators.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using Tyresoles.Sql.Abstractions;");
            sb.AppendLine("using Tyresoles.Sql.GraphQL;");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine($"    public static class {className}QueryExtensions");
            sb.AppendLine("    {");
            sb.AppendLine($"        /// <summary>Converts IQuery to IQueryable for GraphQL (HotChocolate) filtering and sorting; pass the same ITenantScope used to create the query.</summary>");
            sb.AppendLine($"        public static IQueryable<{className}> AsQueryable(this IQuery<{className}> query, Tyresoles.Sql.Abstractions.ITenantScope scope)");
            sb.AppendLine($"            => NavQueryExtensions.AsQueryable(query, scope);");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }
    }
}
